steps:
  # Step 1: Clone your GitHub repo containing source files (.cs, .csproj)
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/20481A04K2/gcpscriptnugetrepo.git']
    dir: '/workspace'

  # Step 2: Use .NET SDK container to download .nupkg, create NuGet config, restore, and publish
  - name: 'mcr.microsoft.com/dotnet/sdk:7.0'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create folder for local NuGet packages
        mkdir -p ~/local-nuget-packages

        # Download your specific .nupkg from GCS bucket to local folder
        gsutil cp gs://my-dotnet-packages/MyDotNetWebApp.1.0.0.nupkg ~/local-nuget-packages/

        # Create NuGet config with local package source and nuget.org fallback
        mkdir -p ~/.nuget/NuGet
        echo "<configuration>
           <packageSources>
              <add key='LocalPackages' value='/root/local-nuget-packages' />
              <add key='nuget.org' value='https://api.nuget.org/v3/index.json' />
           </packageSources>
        </configuration>" > ~/.nuget/NuGet/NuGet.Config

        # Move to project directory
        cd /workspace/gcpscriptnugetrepo

        # Restore using local .nupkg and nuget.org
        dotnet restore MyApp.csproj --configfile ~/.nuget/NuGet/NuGet.Config

        # Publish your app to the 'dist' folder
        dotnet publish MyApp.csproj -c Release -o ./dist

  # Step 3: Upload the published 'dist' folder to your GCS bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r /workspace/gcpscriptnugetrepo/dist/* gs://my-dotnet-packages/dist/

# Enable Cloud Logging for build logs
options:
  logging: CLOUD_LOGGING_ONLY
