steps:
  # Step 1: Download GitHub repo ZIP and extract it
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download GitHub Source'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y unzip
        echo "Downloading GitHub source zip..."
        curl -L -o source.zip https://github.com/20481A04K2/gcpscriptnugetrepo/archive/refs/heads/main.zip
        unzip source.zip -d /workspace
        mv /workspace/gcpscriptnugetrepo-main /workspace/app

  # Step 2: Create NuGet.Config dynamically with BaGet source and API key
  - name: 'mcr.microsoft.com/dotnet/sdk:7.0'
    id: 'Create NuGet Config'
    entrypoint: 'bash'
    secretEnv: ['BAGET_API_KEY']
    args:
      - '-c'
      - |
        echo "Creating NuGet.Config with BaGet source..."
        cat > /workspace/app/NuGet.Config <<EOF
        <?xml version="1.0" encoding="utf-8"?><configuration><packageSources><clear /><add key="baget" value="https://baget-service-880653953247.asia-south1.run.app/v3/index.json" /></packageSources><packageSourceCredentials><baget><add key="Username" value="anyuser" /><add key="ClearTextPassword" value="$$BAGET_API_KEY" /></baget></packageSourceCredentials></configuration>
        EOF

  # Step 3: Restore packages using the created NuGet.Config
  - name: 'mcr.microsoft.com/dotnet/sdk:7.0'
    id: 'Restore Packages from BaGet'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/app
        echo "Restoring packages using BaGet NuGet.Config..."
        dotnet restore MyApp.csproj --configfile NuGet.Config

  # Step 4: Confirm .nupkg packages are cached locally
  - name: 'ubuntu'
    id: 'Verify Nupkg'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking if nupkg files are cached locally..."
        find ~/.nuget/packages -name '*.nupkg' -exec du -h {} \; || echo "No nupkg files found."

  # Step 5: Build and Publish .NET App
  - name: 'mcr.microsoft.com/dotnet/sdk:7.0'
    id: 'Publish App'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/app
        echo "Publishing application..."
        dotnet publish MyApp.csproj -c Release -o dist
        echo "Contents of dist:"
        ls -lh dist

  # Step 6: Upload dist/ to GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload to GCS'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Uploading dist/ to GCS..."
        gsutil -m cp -r /workspace/app/dist/* gs://my-dotnet-packages/dist/

availableSecrets:
  secretManager:
    - versionName: projects/onyx-antler-459216-j6/secrets/baget-api-key/versions/latest
      env: BAGET_API_KEY

options:
  logging: CLOUD_LOGGING_ONLY
